"""Twist 5 CRUD endpoint integration tests (B2)."""
from __future__ import annotations

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from interfaces.api.v1.storyos.dependencies import reset_twist_adapter
from interfaces.api.v1.storyos.error_handlers import register_error_handlers
from interfaces.api.v1.storyos.router_registry import build_storyos_router


@pytest.fixture
def client():
    reset_twist_adapter()
    app = FastAPI()
    register_error_handlers(app)
    app.include_router(build_storyos_router())
    return TestClient(app)


def test_list_twists_empty(client):
    """Empty project returns 200 + empty data envelope."""
    resp = client.get("/api/v1/storyos/proj-new/twist")
    assert resp.status_code == 200
    body = resp.json()
    assert body["data"] == []
    assert body["meta"]["total"] == 0


def test_create_twist_minimal(client):
    """Minimal body creates Twist with autogenerated id; 201 + Response."""
    resp = client.post(
        "/api/v1/storyos/proj-1/twist",
        json={
            "description": "The butler is the long-lost heir",
            "created_chapter": 10,
            "twist_type": "identity_reveal",
        },
    )
    assert resp.status_code == 201
    body = resp.json()
    assert body["description"] == "The butler is the long-lost heir"
    assert body["status"] == "active"
    assert body["twist_type"] == "identity_reveal"
    assert body["reveal_trigger"] is None
    assert body["forbidden_concurrent_twists"] == []
    assert "id" in body and body["id"]
    assert body["project_id"] == "proj-1"
    assert body["created_chapter"] == 10


def test_get_twist_by_id(client):
    """Create -> Get round-trip returns same id."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/twist",
        json={
            "description": "x",
            "created_chapter": 1,
            "twist_type": "betrayal",
        },
    )
    asset_id = create_resp.json()["id"]
    get_resp = client.get(f"/api/v1/storyos/proj-1/twist/{asset_id}")
    assert get_resp.status_code == 200
    assert get_resp.json()["id"] == asset_id


def test_get_twist_not_found_returns_envelope(client):
    """Unknown id -> 404 + ErrorResponse envelope with ASSET_NOT_FOUND."""
    resp = client.get("/api/v1/storyos/proj-1/twist/nonexistent-id")
    assert resp.status_code == 404
    body = resp.json()
    assert body["error"]["code"] == "ASSET_NOT_FOUND"
    assert "nonexistent-id" in body["error"]["message"]


def test_update_twist_partial(client):
    """PATCH with only twist_type updates only that field."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/twist",
        json={
            "description": "x",
            "created_chapter": 1,
            "twist_type": "betrayal",
        },
    )
    asset_id = create_resp.json()["id"]
    patch_resp = client.patch(
        f"/api/v1/storyos/proj-1/twist/{asset_id}",
        json={"twist_type": "sacrifice", "status": "revealed"},
    )
    assert patch_resp.status_code == 200
    body = patch_resp.json()
    assert body["twist_type"] == "sacrifice"
    assert body["status"] == "revealed"
    assert body["description"] == "x"  # unchanged


def test_delete_twist(client):
    """DELETE -> 204; subsequent GET -> 404."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/twist",
        json={
            "description": "x",
            "created_chapter": 1,
            "twist_type": "betrayal",
        },
    )
    asset_id = create_resp.json()["id"]
    del_resp = client.delete(f"/api/v1/storyos/proj-1/twist/{asset_id}")
    assert del_resp.status_code == 204
    get_resp = client.get(f"/api/v1/storyos/proj-1/twist/{asset_id}")
    assert get_resp.status_code == 404


def test_list_twists_with_status_filter(client):
    """status query param filters correctly."""
    client.post(
        "/api/v1/storyos/proj-1/twist",
        json={
            "description": "a",
            "created_chapter": 1,
            "twist_type": "betrayal",
        },
    )
    client.post(
        "/api/v1/storyos/proj-1/twist",
        json={
            "description": "b",
            "created_chapter": 1,
            "twist_type": "sacrifice",
            "status": "revealed",
        },
    )
    resp = client.get("/api/v1/storyos/proj-1/twist?status=revealed")
    assert resp.status_code == 200
    data = resp.json()["data"]
    assert all(t["status"] == "revealed" for t in data)
    assert len(data) == 1


def test_create_twist_rejects_invalid_twist_type(client):
    """twist_type=bogus -> 422 + VALIDATION_ERROR envelope."""
    resp = client.post(
        "/api/v1/storyos/proj-1/twist",
        json={
            "description": "x",
            "created_chapter": 1,
            "twist_type": "bogus_value",
        },
    )
    assert resp.status_code == 422
    body = resp.json()
    assert body["error"]["code"] == "VALIDATION_ERROR"