"""Reveal 5 CRUD endpoint integration tests (B2).

Reveal entity has NO description field; uses ``content`` instead.
Minimal payload: ``{"content": "..."}``.
"""
from __future__ import annotations

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from interfaces.api.v1.storyos.dependencies import reset_reveal_adapter
from interfaces.api.v1.storyos.error_handlers import register_error_handlers
from interfaces.api.v1.storyos.router_registry import build_storyos_router


@pytest.fixture
def client():
    reset_reveal_adapter()
    app = FastAPI()
    register_error_handlers(app)
    app.include_router(build_storyos_router())
    return TestClient(app)


def test_list_reveals_empty(client):
    """Empty project returns 200 + empty data envelope."""
    resp = client.get("/api/v1/storyos/proj-new/reveal")
    assert resp.status_code == 200
    body = resp.json()
    assert body["data"] == []
    assert body["meta"]["total"] == 0


def test_create_reveal_minimal(client):
    """Minimal body creates Reveal with autogenerated id; 201 + Response."""
    resp = client.post(
        "/api/v1/storyos/proj-1/reveal",
        json={
            "content": "The archive holds a deeper truth",
        },
    )
    assert resp.status_code == 201
    body = resp.json()
    assert body["content"] == "The archive holds a deeper truth"
    # Reveal defaults to HIDDEN
    assert body["status"] == "hidden"
    assert body["related_mystery"] is None
    assert body["linked_to_conflict"] is None
    assert body["revealed_in_chapter"] is None
    assert "id" in body and body["id"]
    assert body["project_id"] == "proj-1"


def test_get_reveal_by_id(client):
    """Create -> Get round-trip returns same id."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/reveal",
        json={"content": "x"},
    )
    asset_id = create_resp.json()["id"]
    get_resp = client.get(f"/api/v1/storyos/proj-1/reveal/{asset_id}")
    assert get_resp.status_code == 200
    assert get_resp.json()["id"] == asset_id


def test_get_reveal_not_found_returns_envelope(client):
    """Unknown id -> 404 + ErrorResponse envelope with ASSET_NOT_FOUND."""
    resp = client.get("/api/v1/storyos/proj-1/reveal/nonexistent-id")
    assert resp.status_code == 404
    body = resp.json()
    assert body["error"]["code"] == "ASSET_NOT_FOUND"
    assert "nonexistent-id" in body["error"]["message"]


def test_update_reveal_partial(client):
    """PATCH with only status updates only that field."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/reveal",
        json={"content": "x"},
    )
    asset_id = create_resp.json()["id"]
    patch_resp = client.patch(
        f"/api/v1/storyos/proj-1/reveal/{asset_id}",
        json={"status": "revealed", "revealed_in_chapter": 5},
    )
    assert patch_resp.status_code == 200
    body = patch_resp.json()
    assert body["status"] == "revealed"
    assert body["revealed_in_chapter"] == 5
    assert body["content"] == "x"  # unchanged


def test_delete_reveal(client):
    """DELETE -> 204; subsequent GET -> 404."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/reveal",
        json={"content": "x"},
    )
    asset_id = create_resp.json()["id"]
    del_resp = client.delete(f"/api/v1/storyos/proj-1/reveal/{asset_id}")
    assert del_resp.status_code == 204
    get_resp = client.get(f"/api/v1/storyos/proj-1/reveal/{asset_id}")
    assert get_resp.status_code == 404


def test_list_reveals_with_status_filter(client):
    """status query param filters correctly."""
    client.post(
        "/api/v1/storyos/proj-1/reveal",
        json={"content": "a"},
    )
    client.post(
        "/api/v1/storyos/proj-1/reveal",
        json={"content": "b", "status": "revealed", "revealed_in_chapter": 7},
    )
    resp = client.get("/api/v1/storyos/proj-1/reveal?status=revealed")
    assert resp.status_code == 200
    data = resp.json()["data"]
    assert all(r["status"] == "revealed" for r in data)
    assert len(data) == 1


def test_create_reveal_rejects_missing_content(client):
    """content is required; missing it -> 422 + VALIDATION_ERROR envelope."""
    resp = client.post(
        "/api/v1/storyos/proj-1/reveal",
        json={"status": "active"},
    )
    assert resp.status_code == 422
    body = resp.json()
    assert body["error"]["code"] == "VALIDATION_ERROR"