"""Foreshadowing 5 CRUD endpoint integration tests (B2).

Foreshadowing requires ``planted_in_chapter``; ``importance`` defaults to MEDIUM.
"""
from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from interfaces.main import app
from interfaces.api.v1.storyos.dependencies import reset_foreshadowing_adapter


@pytest.fixture
def client():
    reset_foreshadowing_adapter()
    return TestClient(app)


def test_list_foreshadowings_empty(client):
    """Empty project returns 200 + empty data envelope."""
    resp = client.get("/api/v1/storyos/proj-new/foreshadowing")
    assert resp.status_code == 200
    body = resp.json()
    assert body["data"] == []
    assert body["meta"]["total"] == 0


def test_create_foreshadowing_minimal(client):
    """Minimal body creates Foreshadowing with autogenerated id; 201 + Response."""
    resp = client.post(
        "/api/v1/storyos/proj-1/foreshadowing",
        json={
            "description": "The cracked locket will matter later",
            "planted_in_chapter": 1,
        },
    )
    assert resp.status_code == 201
    body = resp.json()
    assert body["description"] == "The cracked locket will matter later"
    assert body["status"] == "planted"
    # ImportanceLevel.MEDIUM = 2 (IntEnum)
    assert body["importance"] == 2
    assert body["planted_in_chapter"] == 1
    assert body["suggested_resolve_chapter"] is None
    assert body["resolved_in_chapter"] is None
    assert body["project_id"] == "proj-1"
    assert "id" in body and body["id"]


def test_get_foreshadowing_by_id(client):
    """Create -> Get round-trip returns same id."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/foreshadowing",
        json={"description": "x", "planted_in_chapter": 1},
    )
    asset_id = create_resp.json()["id"]
    get_resp = client.get(f"/api/v1/storyos/proj-1/foreshadowing/{asset_id}")
    assert get_resp.status_code == 200
    assert get_resp.json()["id"] == asset_id


def test_get_foreshadowing_not_found_returns_envelope(client):
    """Unknown id -> 404 + ErrorResponse envelope with ASSET_NOT_FOUND."""
    resp = client.get("/api/v1/storyos/proj-1/foreshadowing/nonexistent-id")
    assert resp.status_code == 404
    body = resp.json()
    assert body["error"]["code"] == "ASSET_NOT_FOUND"
    assert "nonexistent-id" in body["error"]["message"]


def test_update_foreshadowing_partial(client):
    """PATCH with only importance updates only that field."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/foreshadowing",
        json={"description": "x", "planted_in_chapter": 1},
    )
    asset_id = create_resp.json()["id"]
    patch_resp = client.patch(
        f"/api/v1/storyos/proj-1/foreshadowing/{asset_id}",
        json={"importance": 3, "status": "revealed", "resolved_in_chapter": 10},
    )
    assert patch_resp.status_code == 200
    body = patch_resp.json()
    # ImportanceLevel.HIGH = 3
    assert body["importance"] == 3
    assert body["status"] == "revealed"
    assert body["resolved_in_chapter"] == 10
    assert body["description"] == "x"  # unchanged


def test_delete_foreshadowing(client):
    """DELETE -> 204; subsequent GET -> 404."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/foreshadowing",
        json={"description": "x", "planted_in_chapter": 1},
    )
    asset_id = create_resp.json()["id"]
    del_resp = client.delete(f"/api/v1/storyos/proj-1/foreshadowing/{asset_id}")
    assert del_resp.status_code == 204
    get_resp = client.get(f"/api/v1/storyos/proj-1/foreshadowing/{asset_id}")
    assert get_resp.status_code == 404


def test_list_foreshadowings_with_status_filter(client):
    """status query param filters correctly."""
    client.post(
        "/api/v1/storyos/proj-1/foreshadowing",
        json={"description": "a", "planted_in_chapter": 1},
    )
    client.post(
        "/api/v1/storyos/proj-1/foreshadowing",
        json={
            "description": "b",
            "planted_in_chapter": 2,
            "status": "abandoned",
        },
    )
    resp = client.get("/api/v1/storyos/proj-1/foreshadowing?status=abandoned")
    assert resp.status_code == 200
    data = resp.json()["data"]
    assert all(f["status"] == "abandoned" for f in data)
    assert len(data) == 1


def test_create_foreshadowing_rejects_invalid_status(client):
    """status=bogus -> 422 + VALIDATION_ERROR envelope."""
    resp = client.post(
        "/api/v1/storyos/proj-1/foreshadowing",
        json={
            "description": "x",
            "planted_in_chapter": 1,
            "status": "bogus_value",
        },
    )
    assert resp.status_code == 422
    body = resp.json()
    assert body["error"]["code"] == "VALIDATION_ERROR"