"""Conflict 5 CRUD endpoint integration tests (B1 happy path + 4 error paths)."""
from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from interfaces.main import app
from interfaces.api.v1.storyos.dependencies import reset_conflict_adapter


@pytest.fixture
def client():
    reset_conflict_adapter()
    return TestClient(app)


def test_list_conflicts_empty(client):
    """Empty project returns 200 + empty data envelope."""
    resp = client.get("/api/v1/storyos/proj-new/conflict")
    assert resp.status_code == 200
    body = resp.json()
    assert body["data"] == []
    assert body["meta"]["total"] == 0


def test_create_conflict_minimal(client):
    """Minimal body creates Conflict with autogenerated id; 201 + Response."""
    resp = client.post(
        "/api/v1/storyos/proj-1/conflict",
        json={
            "description": "Lin Yuan vs Shen Mo power struggle",
            "created_chapter": 3,
        },
    )
    assert resp.status_code == 201
    body = resp.json()
    assert body["description"] == "Lin Yuan vs Shen Mo power struggle"
    assert body["status"] == "active"
    # ConflictIntensity.MEDIUM serializes as its enum int (2).
    assert body["intensity"] == 2
    assert "id" in body and body["id"]
    assert body["project_id"] == "proj-1"
    assert body["created_chapter"] == 3


def test_get_conflict_by_id(client):
    """Create -> Get round-trip returns same id."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/conflict",
        json={"description": "x", "created_chapter": 1},
    )
    asset_id = create_resp.json()["id"]
    get_resp = client.get(f"/api/v1/storyos/proj-1/conflict/{asset_id}")
    assert get_resp.status_code == 200
    assert get_resp.json()["id"] == asset_id


def test_get_conflict_not_found_returns_envelope(client):
    """Unknown id -> 404 + ErrorResponse envelope with ASSET_NOT_FOUND."""
    resp = client.get("/api/v1/storyos/proj-1/conflict/nonexistent-id")
    assert resp.status_code == 404
    body = resp.json()
    assert body["error"]["code"] == "ASSET_NOT_FOUND"
    assert "nonexistent-id" in body["error"]["message"]


def test_update_conflict_partial(client):
    """PATCH with only status updates only that field."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/conflict",
        json={
            "description": "x",
            "created_chapter": 1,
            "intensity": 2,
        },
    )
    asset_id = create_resp.json()["id"]
    patch_resp = client.patch(
        f"/api/v1/storyos/proj-1/conflict/{asset_id}",
        json={"status": "escalated", "intensity": 3},
    )
    assert patch_resp.status_code == 200
    body = patch_resp.json()
    assert body["status"] == "escalated"
    # ConflictIntensity.HIGH = 3
    assert body["intensity"] == 3
    assert body["description"] == "x"  # unchanged


def test_delete_conflict(client):
    """DELETE -> 204; subsequent GET -> 404."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/conflict",
        json={"description": "x", "created_chapter": 1},
    )
    asset_id = create_resp.json()["id"]
    del_resp = client.delete(f"/api/v1/storyos/proj-1/conflict/{asset_id}")
    assert del_resp.status_code == 204
    get_resp = client.get(f"/api/v1/storyos/proj-1/conflict/{asset_id}")
    assert get_resp.status_code == 404


def test_list_conflicts_with_status_filter(client):
    """status query param filters correctly."""
    client.post(
        "/api/v1/storyos/proj-1/conflict",
        json={"description": "a", "created_chapter": 1},
    )
    client.post(
        "/api/v1/storyos/proj-1/conflict",
        json={"description": "b", "created_chapter": 1, "status": "escalated"},
    )
    resp = client.get("/api/v1/storyos/proj-1/conflict?status=escalated")
    assert resp.status_code == 200
    data = resp.json()["data"]
    assert all(c["status"] == "escalated" for c in data)
    assert len(data) == 1


def test_create_conflict_rejects_intensity_out_of_range(client):
    """intensity=bogus -> 422 + VALIDATION_ERROR envelope."""
    resp = client.post(
        "/api/v1/storyos/proj-1/conflict",
        json={
            "description": "x",
            "created_chapter": 1,
            "intensity": "bogus_value",
        },
    )
    assert resp.status_code == 422
    body = resp.json()
    assert body["error"]["code"] == "VALIDATION_ERROR"
