"""Expectation 5 CRUD endpoint integration tests (B2).

Expectation requires ``intensity`` (0..100) at creation time.
"""
from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from interfaces.main import app
from interfaces.api.v1.storyos.dependencies import reset_expectation_adapter


@pytest.fixture
def client():
    reset_expectation_adapter()
    return TestClient(app)


def test_list_expectations_empty(client):
    """Empty project returns 200 + empty data envelope."""
    resp = client.get("/api/v1/storyos/proj-new/expectation")
    assert resp.status_code == 200
    body = resp.json()
    assert body["data"] == []
    assert body["meta"]["total"] == 0


def test_create_expectation_minimal(client):
    """Minimal body creates Expectation with autogenerated id; 201 + Response."""
    resp = client.post(
        "/api/v1/storyos/proj-1/expectation",
        json={
            "description": "Reader expects the hero to win",
            "created_chapter": 1,
            "intensity": 70,
        },
    )
    assert resp.status_code == 201
    body = resp.json()
    assert body["description"] == "Reader expects the hero to win"
    assert body["status"] == "active"
    assert body["intensity"] == 70
    assert body["created_chapter"] == 1
    assert body["project_id"] == "proj-1"
    assert "id" in body and body["id"]


def test_get_expectation_by_id(client):
    """Create -> Get round-trip returns same id."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/expectation",
        json={"description": "x", "created_chapter": 1, "intensity": 50},
    )
    asset_id = create_resp.json()["id"]
    get_resp = client.get(f"/api/v1/storyos/proj-1/expectation/{asset_id}")
    assert get_resp.status_code == 200
    assert get_resp.json()["id"] == asset_id


def test_get_expectation_not_found_returns_envelope(client):
    """Unknown id -> 404 + ErrorResponse envelope with ASSET_NOT_FOUND."""
    resp = client.get("/api/v1/storyos/proj-1/expectation/nonexistent-id")
    assert resp.status_code == 404
    body = resp.json()
    assert body["error"]["code"] == "ASSET_NOT_FOUND"
    assert "nonexistent-id" in body["error"]["message"]


def test_update_expectation_partial(client):
    """PATCH with only intensity updates only that field."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/expectation",
        json={"description": "x", "created_chapter": 1, "intensity": 30},
    )
    asset_id = create_resp.json()["id"]
    patch_resp = client.patch(
        f"/api/v1/storyos/proj-1/expectation/{asset_id}",
        json={"intensity": 80, "status": "fulfilled"},
    )
    assert patch_resp.status_code == 200
    body = patch_resp.json()
    assert body["intensity"] == 80
    assert body["status"] == "fulfilled"
    assert body["description"] == "x"  # unchanged


def test_delete_expectation(client):
    """DELETE -> 204; subsequent GET -> 404."""
    create_resp = client.post(
        "/api/v1/storyos/proj-1/expectation",
        json={"description": "x", "created_chapter": 1, "intensity": 50},
    )
    asset_id = create_resp.json()["id"]
    del_resp = client.delete(f"/api/v1/storyos/proj-1/expectation/{asset_id}")
    assert del_resp.status_code == 204
    get_resp = client.get(f"/api/v1/storyos/proj-1/expectation/{asset_id}")
    assert get_resp.status_code == 404


def test_list_expectations_with_status_filter(client):
    """status query param filters correctly."""
    client.post(
        "/api/v1/storyos/proj-1/expectation",
        json={"description": "a", "created_chapter": 1, "intensity": 20},
    )
    client.post(
        "/api/v1/storyos/proj-1/expectation",
        json={
            "description": "b",
            "created_chapter": 2,
            "intensity": 90,
            "status": "fulfilled",
        },
    )
    resp = client.get("/api/v1/storyos/proj-1/expectation?status=fulfilled")
    assert resp.status_code == 200
    data = resp.json()["data"]
    assert all(e["status"] == "fulfilled" for e in data)
    assert len(data) == 1


def test_create_expectation_rejects_intensity_out_of_range(client):
    """intensity=150 (>100) -> 422 + VALIDATION_ERROR envelope."""
    resp = client.post(
        "/api/v1/storyos/proj-1/expectation",
        json={
            "description": "x",
            "created_chapter": 1,
            "intensity": 150,
        },
    )
    assert resp.status_code == 422
    body = resp.json()
    assert body["error"]["code"] == "VALIDATION_ERROR"